language: python
python:
#  - 2.6
#  - 2.7
#  - 3.2
#  - 3.3
#  - 3.4
  - 3.5
#  - nightly

addons:
  apt:
    packages:
      - xpra

before_install:
#  - export DISPLAY=:99.0
#  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- +extension RANDR :99 -ac -screen 0 1280x1024x16
  - xpra --xvfb="Xorg +extension RANDR -config `pwd`/tests/dummy.xorg.conf -logfile ~/.xpra/xorg.log" start :99

install:
  - python setup.py install

script: py.test --display=":99.0"

after_script:
  - xpra stop :99
  - cat ~/.xpra/xorg.log

matrix:
    fast_finish: true

