language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6-dev
  - nightly # currently points to 3.7-dev

addons:
  apt:
    packages:
      - xpra
      - xserver-xorg-video-dummy

before_install:
  - xpra --xvfb="Xorg +extension RANDR -config `pwd`/tests/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log" start :42

install:
  - pip install flake8
  - python setup.py install

script:
  - py.test --display=":42.0"
  - flake8 mss
#  - mypy --check-untyped-defs --warn-incomplete-stub -m mss

after_script:
  - xpra stop :42
  - cat ~/.xpra/*.log

matrix:
    fast_finish: true
