language: python
python:
#  - 2.6
#  - 2.7
#  - 3.2
#  - 3.3
#  - 3.4
  - 3.5
#  - nightly

addons:
  apt:
    packages:
      - xpra
      - xserver-xorg-video-dummy

before_install:
  - xpra --xvfb="Xorg +extension RANDR -config `pwd`/tests/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log" start :42

install:
  - python setup.py install

script: py.test --display=":42.0"

after_script:
  - xpra stop :42
  - cat ~/.xpra/*.log

matrix:
    fast_finish: true
