language: python
python:
#  - 2.6
#  - 2.7
#  - 3.2
#  - 3.3
#  - 3.4
  - 3.5
#  - nightly

before_install:
  - export DISPLAY=:99.0
  - sudo /etc/init.d/xvfb stop
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- +extension RANDR :99 -ac -screen 0 1280x1024x16
  - sudo /etc/init.d/xvfb start

install:
  - python setup.py install

script: py.test --display=":99.0"

matrix:
    fast_finish: true

